export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';

export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS';

export const FETCH_INBOX_DETAILS = 'FETCH_INBOX_DETAILS';
export const FETCH_INBOX_DETAILS_SUCCESS = 'FETCH_INBOX_DETAILS_SUCCESS';

export const FETCH_EMAILS = 'FETCH_EMAILS';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_ERROR = 'FETCH_EMAILS_ERROR';

export const DELETE_EMAILS = 'DELETE_EMAILS';
export const DELETE_EMAILS_SUCCESS = 'DELETE_EMAILS_SUCCESS';
export const DELETE_EMAILS_ERROR = 'DELETE_EMAILS_ERROR';

export const READ_EMAILS = 'READ_EMAILS';
export const READ_EMAILS_SUCCESS = 'READ_EMAILS_SUCCESS';
export const READ_EMAILS_ERROR = 'READ_EMAILS_ERROR';
