export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';
export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS';

export const FETCH_INBOX_DETAILS = 'FETCH_INBOX_DETAILS';
export const FETCH_INBOX_DETAILS_SUCCESS = 'FETCH_INBOX_DETAILS_SUCCESS';
export const FETCH_INBOX_DETAILS_ERROR = 'FETCH_INBOX_DETAILS_ERROR';
export const FETCH_INBOX_EMAILS = 'FETCH_INBOX_EMAILS';
export const FETCH_INBOX_EMAILS_SUCCESS = 'FETCH_INBOX_EMAILS_SUCCESS';
